runtime: python37
# inbound_services:
# - warmup

entrypoint: >
  gunicorn -b :$PORT main:app

automatic_scaling:
  max_instances: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  expiration: 30d
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /(apple-touch-icon.*\.(png))
  static_files: static/\1
  upload: static/(apple-touch-icon.*\.png)
  expiration: 30d
- url: /images
  static_dir: static/images
  expiration: 14d
- url: /css
  static_dir: static/css
  expiration: 7d
- url: /js
  static_dir: static/js
  expiration: 7d
- url: /fonts
  static_dir: static/fonts
  expiration: 30d

error_handlers:
- error_code: over_quota
  file: error_pages/over_quota.html

env_variables:
    TZ: 'UTC'
